# This makefile is used as follows to regenerate files for the register program:
# make register   --  regenerates the executable register file by compiling
# make 			  --  same as "make register"

register: coffee_shop.c register.c register.h
	gcc coffee_shop.c register.c -o register